<?php

/**
 * @file
 * The TM Flex Group Conference module.
 */

/**
 * Provide a method to alter array of group types used in open social.
 *
 * @param array $social_group_types
 *   List of group types used in open social.
 *
 * @ingroup social_group_api
 */
function tm_flex_group_conference_social_group_types_alter(array &$social_group_types) {
  $social_group_types[] = 'tm_conference';
}

/**
 * Provide a method to extend group and content visibility to other group types.
 *
 * @param string $social_group_types
 *   The group type id.
 *
 * @ingroup social_group_api
 */
function tm_flex_group_training_social_group_settings_alter(&$social_group_types) {
  $social_group_types[] = 'tm_conference';
}

